### ISSUE TITLE
Annotation Validation Bug 1

### ISSUE THREAD

**Issue by gr3ysky** [swe574-group2/swe574#48]
Description: When we validate the annotation using the validation tool we get the following error.

> 1:44 If present **Specific Resource _selector_ key** has one or more values each of which is of **format uri** or an object having a **_type_ key** with a **single value** which is one of **'FragmentSelector', 'CssSelector', 'XPathSelector', 'TextQuoteSelector', 'TextPositionSelector', 'DataPositionSelector', 'SvgSelector', 'RangeSelector'** - [model 4.2](https://www.w3.org/TR/annotation-model/#selectors)	assert_true: ERROR: Annotation contains one or more Specific Resources selectors having value(s) which is(are) not of format uri, nor an object having a type key with a single value which is one of 'FragmentSelector', 'CssSelector', 'XPathSelector', 'TextQuoteSelector', 'TextPositionSelector', 'DataPositionSelector', 'SvgSelector', 'RangeSelector'.; expected true got false
    at JSONtest.<anonymous> (http://w3c-test.org/annotation-model/scripts/JSONtest.js:545:17)
    at Test.step (http://w3c-test.org/resources/testharness.js:1406:25)
    at test (http://w3c-test.org/resources/testharness.js:501:18)
    at JSONtest.<anonymous> (http://w3c-test.org/annotation-model/scripts/JSONtest.js:533:13)
    at Array.forEach (native)
    at JSONtest.runTests (http://w3c-test.org/annotation-model/scripts/JSONtest.js:408:18)

tool url: http://w3c-test.org/annotation-model/annotations/annotationMusts-manual.html

Estimated Effort: 2 hours

**Comment by gr3ysky** [comment]
Sample json-ld

{"target":{"source":"http://w3c-test.org/resources/testharness.js","selector":{"type":"TextPositionSelector","start":"247","end":"265","value":"tium/Legal/2008/04"}},"type":"Annotation","id":"http://w3c-test.org/resources/testharness.js","@context":"http://www.w3.org/ns/anno.jsonld","private":"on","motivation":"assessing","creator":{"name":"admin","nickname":"admin"},"generator":{"name":"CatPlugin","homePage":"www.catplugin.net"},"body":{"value":"", "type": "SpecificResource","purpose":"assessing","annotationSource":"catplugin"}}

**Comment by gr3ysky** [comment]
Since this is an error with the valitador itself, I am closing the issue
