### ISSUE TITLE
Annotation Validation Bug 2

### ISSUE THREAD

**Issue by gr3ysky** [swe574-group2/swe574#49]
Description: When we validate the annotation using the validation tool we get the following error.

> 1:50 If present all **Selectors of _type_ TextPositionSelector or DataPositionSelector** have both a **_start_ key** and an **_end_ key**, each with a **single non-negative integer value** [model 4.2](https://www.w3.org/TR/annotation-model/#selectors)	assert_true: ERROR: Annotation contains a Text Position or Data Position selector that is NOT of format uri and NOT an object having a value key with a single sting value.; expected true got false
    at JSONtest.<anonymous> (http://w3c-test.org/annotation-model/scripts/JSONtest.js:545:17)
    at Test.step (http://w3c-test.org/resources/testharness.js:1406:25)
    at test (http://w3c-test.org/resources/testharness.js:501:18)
    at JSONtest.<anonymous> (http://w3c-test.org/annotation-model/scripts/JSONtest.js:533:13)
    at Array.forEach (native)
    at JSONtest.runTests (http://w3c-test.org/annotation-model/scripts/JSONtest.js:408:18

tool url: http://w3c-test.org/annotation-model/annotations/annotationMusts-manual.html

Estimated Effort: 2 hours

**Comment by gr3ysky** [comment]
Sample json-ld

{"target":{"source":"http://w3c-test.org/resources/testharness.js","selector":{"type":"TextPositionSelector","start":"247","end":"265","value":"tium/Legal/2008/04"}},"type":"Annotation","id":"http://w3c-test.org/resources/testharness.js","@context":"http://www.w3.org/ns/anno.jsonld","private":"on","motivation":"assessing","creator":{"name":"admin","nickname":"admin"},"generator":{"name":"CatPlugin","homePage":"www.catplugin.net"},"body":{"value":"", "type": "SpecificResource","purpose":"assessing","annotationSource":"catplugin"}}

**Comment by gr3ysky** [comment]
since this is an error with the valitador itself, I am closing the issue.
